### PR TITLE
Upgrade to NextJS 8, React 16.8, Emotion 10, Sequelize 5 

### PR DESCRIPTION
**Pull request by huyhong**

### CODE REVIEW

**Comment by pruhstal** [comment]
@huyhong funny seeing you here 😂

**Comment by huyhong** [comment]
@pruhstal lol just trying to give back a little bit :), I think I noticed this package cause of your follow or star in my feed

**Comment by pruhstal** [comment]
This repo is the best and so is @jimmylee (and of course you for contributing to it). 

Hope you're doing well!

**Comment by jimmylee** [comment]
Thanks for the contribution! Sorry for the delay I'm looking through things now.

**Comment by jimmylee** [comment]
@huyhong thanks for doing this. I'm still concerned about some migration breakage between Emotion 9.1 and Emotion 10 but I'm going to land this so we can deal with those issues on master (if they come up).

Really appreciate it!

**Comment by huyhong** [comment]
@jimmylee no worries, thanks for keeping this repo in shape

**Pull request merged**
